name: dynamic-express-boilerplate

services:
  logger:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logger
    image: express-logger
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - dynamic-express-boilerplate
    restart: always

networks:
  dynamic-express-boilerplate:
    driver: bridge
