name: express-logger

services:
  logger:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logger
    image: express-logger
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - express-logger
    restart: always

networks:
  express-logger:
    driver: bridge
